---
- hosts: localhost
  become: true
  tasks:
      - name: Update golang repo
        apt_repository:
            repo: ppa:longsleep/golang-backports
#        shell: apt-add-repository -y --update ppa:longsleep/golang-backports

      - name: Install General Utilities
        apt:
            name: [
                clang,
                clang-tidy,
                cmake,
                gdb,
                git,
                golang,
                htop,
                nasm,
                openssh-client,
                pycodestyle,
                pydocstyle,
                pylint,
                python3,
                python3-pip,
                strace,
                tmux,
                valgrind,
                vim,
                wget,
                wireshark
            ]

      - name: Install ZSH
        apt: name=zsh

      - name: Change default shell
        shell: chsh -s $(which zsh)

      - name: Install ohmyzsh
        shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

