---
- hosts: localhost
  tasks:
      - name: Install General Utilities
        apt: name={{item}}
        with_items:
            - htop
            - tmux
            - vim
            - clang
            - clang-tidy
            - cmake
            - valgrind
            - gdb
            - strace
            - git
            - python3
            - openssh-client
            - wget
            - nasm
            - wireshark

      - name: Installing pip3 Packages
        pip3: name={{item}}
        with_items:
            - pylint
            - pydocstyle
            - pycodestyle

      - name: Build cmake
        shell: cd cunit && cmake -H. -Bbuild && cmake --build build && cmake --install build

      - name: Install oh-my-zsh
        apt: name=zsh
        shell: chsh -s $(which zsh)
        shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

