---
- hosts: localhost
  become: true
  tasks:
      - name: Update golang repo
        apt_repository:
            repo: ppa:longsleep/golang-backports

      - name: Install General Utilities
        apt:
            name: [
                clang,
                clang-tidy,
                cmake,
                gdb,
                golang,
                htop,
                nasm,
                nodejs,
                npm,
                openssh-client,
                pycodestyle,
                pydocstyle,
                pylint,
                python3,
                python3-pip,
                strace,
                tmux,
                valgrind,
                vim,
                wget,
                wireshark,
                zsh
            ]

      - name: Change default shell
        shell: chsh -s $(which zsh)

      - name: Install ohmyzsh
        shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

      - name: Setup CAC Support
        become: true
        shell: sudo sh -c "$(wget https://raw.githubusercontent.com/jdjaxon/linux_cac/main/cac_setup.sh -O -)"

      - name: Install Docker
        become: true
        shell: sh -c "$(wget https://get.docker.com -O -)"

      - name: Install Yarn
        npm:
            name: yarn
            global: yes

      - name: Install eslint
        npm:
            name: eslint
            global: yes

      - name: Install Typescript
        npm:
            name: typescript
            global: yes

      - name: Install n
        npm:
            name: n
            global: yes

      - name: Set npm version
        shell: n 14

