- hosts: localhost
  become: yes
  vars:
    home: "{{ ansible_env.HOME }}"

  tasks:
    - name: Update Apt
      apt:
        update_cache: yes
    - include_tasks: tasks/general.yml
    # - include_tasks: tasks/cac_setup.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/c.yml
    - include_tasks: tasks/python.yml
    - include_tasks: tasks/golang.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/node.yml
    # - include_tasks: tasks/postgres.yml
    # - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/editors.yml
