- hosts: localhost
  become: yes
  vars:
    home: "{{ ansible_env.HOME }}"

  tasks:
    - name: Update Apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - include_tasks: tasks/general.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/c.yml
    - include_tasks: tasks/python.yml
    - include_tasks: tasks/golang.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/dotfiles.yml
