---
- hosts: localhost
  become: true
  tasks:
      - name: Install General Utilities
        apt:
            name: [
                htop,
                tmux,
                vim,
                clang,
                clang-tidy,
                cmake,
                valgrind,
                gdb,
                strace,
                git,
                python3,
                openssh-client,
                wget,
                nasm,
                wireshark,
                pylint,
                pydocstyle,
                pycodestyle
            ]

      - name: Install ZSH
        apt: name=zsh

      - name: Change default shell
        shell: chsh -s $(which zsh)

      - name: Install ohmyzsh
        shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

