---
- name: Standardizing development environment
  hosts: localhost
  become: true
  tasks:
    - include: general.yml
    - include: zsh.yml
    - include: vim.yml
    - include: c.yml
    - include: python.yml
    - include: golang.yml
    - include: node.yml
    - include: cac_setup.yml
    - include: docker.yml
