- hosts: localhost
  become: yes
  vars:
    home: "{{ ansible_env.HOME }}"
    tasks_files:
      - tasks/general.yml
      - tasks/zsh.yml
      - tasks/c.yml
      - tasks/python.yml
      - tasks/golang.yml
      - tasks/docker.yml

  tasks:
    - name: Update Apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Include task files
      include_tasks: "{{ item }}"
      loop: "{{ task_files }}"
