---
- hosts: localhost
  become: true
  tasks:
      - name: Update golang repo
        apt_repository:
            repo: ppa:longsleep/golang-backports

      - name: Install C Software
        apt:
            name: [
                clang,
                clang-tidy,
                cmake,
            ]

      - name: Install Debugging Software
        apt:
            name: [
                gdb,
                valgrind,
                git,
                golang,
            ]

      - name: Install Python Software
        apt:
            name: [
                pycodestyle,
                pydocstyle,
                pylint,
                python3,
                python3-pip,
            ]

      - name: Install General Utilities
        apt:
            name: [
                htop,
                nasm,
                openssh-client,
                strace,
                tmux,
                vim,
                wget,
                wireshark
            ]

      - name: Install ZSH
        apt: name=zsh

      - name: Change default shell
        shell: chsh -s $(which zsh)

      - name: Install ohmyzsh
        shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"

