---
- name: Standardizing development environment
  hosts: localhost
  become: true
  tasks:
    - include: tasks/general.yml
    - include: tasks/zsh.yml
    - include: tasks/vim.yml
    - include: tasks/c.yml
    - include: tasks/python.yml
    - include: tasks/golang.yml
    - include: tasks/node.yml
    - include: tasks/cac_setup.yml
    - include: tasks/docker.yml
