- name: Install nodejs and npm
  apt:
    name:
      - nodejs
      - npm
    state: present
    update_cache: yes

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
    unsafe_perm: yes
  loop:
    - yarn
    - eslint
    - typescript
    - n

- name: Install Vue.js
  npm:
    name: "@vue/cli"
    global: yes
