- name: Install Python and Associated Utilities
  apt:
    name:
      - python3
      - python3-pip
      - pycodestyle
      - pydocstyle
      - pylint
    state: present
    update_cache: yes

- name: Install ruff via pip
  pip:
    name: ruff
    executable: pip3
