- name: Install ZSH
  apt:
    name: zsh

- name: Change default shell to ZSH
  command: chsh -s "$(which zsh)"
  when: ansible_env.SHELL != "/bin/zsh"

- name: Install ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: "{{ home }}/.oh-my-installer"
    mode: '0755'

- name: Run oh-my-zsh installer
  command: "{{ home }}/.oh-my-installer"
  args:
    creates: "{{ home }}/.oh-my-zsh"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
