- name: Install General Utilities
  apt:
    name: zsh

- name: Change default shell
  shell: chsh -s $(which zsh)

- name: Install ohmyzsh
  shell: sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
